### ISSUE TITLE
ATAG social media brief

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-intro-atag#34]
Hi Daniel, 

just a couple of points which are jumping out at me: 

Perhaps the intro line could be more specific?  
This page briefly introduces a standard to help you make your social media platform accessible to creators and users with disabilities.

Some suggestions for the personas, this is all off the top of my head, it isn't polished at all! 

For the first persona, I still think it needs to be more rooted in the context. At the moment, it could be any of the three scenarios (education, etc.) Thinking about how social media consultants do their jobs, it's more than just managing a profile, maybe adding in one element of that will help, so something about uploading and managing multiple images maybe? Or perhaps some kind of administrator in a team who handles customer messages via social media? (This is just off the top of my head, but I can keep thinking about it.) and then it'd need to be more closely aligned to the context in the final part to make it more specific than 'to do their job'. 

Persona: Banele is a social media consultant with low vision. She uses magnification software to increase the font size of the tools she uses.

    Problem: " I used to be able to read through client messages through our social media platform with my magnification software. Unfortunately, after the last update, my magnification software no longer works, so I can't read with text at the size I need."

    Works well: " Tool updates preserve accessibility features. If something ever breaks, I can go back to the previous version of the tool where it worked as expected. "

Users who have auditory, cognitive, neurological, physical, speech, and visual disabilities often rely on robust platforms which work with the assistive technology they use. You need to ensure accessibility is preserved when updating your tool’s user interface or functionality.

In the second persona, the reason I added the part about comments and reacting and responding to comments, again was to tie it more closely to the context, an influencer needs to do more than refresh and read content, the reason they're an influencer is because they're engaging with the content. I'd put that part back in there. 

Persona: Nushi is an influencer with reading disabilities. He uses tools to have text read aloud.

    Problem: " When content refreshes too fast, I have problems keeping up-to-date and it makes it difficult to manage new comments."

    Works well: " I can decide when to have new content appear. This way I can read at my own pace, use tools to read content aloud if needed, and make sure I'm reacting and responding to my followers when I need to. "

People who use social media have different abilities. For example, they may read content at different paces. Your tool should allow them to decide how they want to process the new content that appears.

For the final persona, I think that needs editing to make it less general. 

Persona: Enhamed manages the social media profile of a small business. He has just started thinking about the accessibility of the content he uploads.

    Problem: " I get complaints from customers that our links, images and videos are not accessible. I can't do anything about it because my tool does not allow me to add these features. "

    Works well: " I can add alt text for my images, show captions for my videos, and write custom text for my links. "

People who upload different types of content need tools that can create accessible social experiences. This includes adding alternatives to images and multimedia and using a clear link text that explains what the link is about.

**Comment by daniel-montalvo** [comment]
Thanks much @jade-mc 

Adding these as GitHub tasks below.

- [ ] Perhaps the intro line could be more specific?  
  This page briefly introduces a standard to help you make your social media platform accessible to creators and users with disabilities.

Some suggestions for the personas, this is all off the top of my head, it isn't polished at all! 

- [ ] For the first persona, I still think it needs to be more rooted in the context. At the moment, it could be any of the three scenarios (education, etc.) Thinking about how social media consultants do their jobs, it's more than just managing a profile, maybe adding in one element of that will help, so something about uploading and managing multiple images maybe? Or perhaps some kind of administrator in a team who handles customer messages via social media? (This is just off the top of my head, but I can keep thinking about it.) and then it'd need to be more closely aligned to the context in the final part to make it more specific than 'to do their job'. 

Persona: Banele is a social media consultant with low vision. She uses magnification software to increase the font size of the tools she uses.

    Problem: " I used to be able to read through client messages through our social media platform with my magnification software. Unfortunately, after the last update, my magnification software no longer works, so I can't read with text at the size I need."

    Works well: " Tool updates preserve accessibility features. If something ever breaks, I can go back to the previous version of the tool where it worked as expected. "

Users who have auditory, cognitive, neurological, physical, speech, and visual disabilities often rely on robust platforms which work with the assistive technology they use. You need to ensure accessibility is preserved when updating your tool’s user interface or functionality.

- [ ] In the second persona, the reason I added the part about comments and reacting and responding to comments, again was to tie it more closely to the context, an influencer needs to do more than refresh and read content, the reason they're an influencer is because they're engaging with the content. I'd put that part back in there. 

Persona: Nushi is an influencer with reading disabilities. He uses tools to have text read aloud.

    Problem: " When content refreshes too fast, I have problems keeping up-to-date and it makes it difficult to manage new comments."

    Works well: " I can decide when to have new content appear. This way I can read at my own pace, use tools to read content aloud if needed, and make sure I'm reacting and responding to my followers when I need to. "

People who use social media have different abilities. For example, they may read content at different paces. Your tool should allow them to decide how they want to process the new content that appears.

- [ ] For the final persona, I think that needs editing to make it less general. 

Persona: Enhamed manages the social media profile of a small business. He has just started thinking about the accessibility of the content he uploads.

    Problem: " I get complaints from customers that our links, images and videos are not accessible. I can't do anything about it because my tool does not allow me to add these features. "

    Works well: " I can add alt text for my images, show captions for my videos, and write custom text for my links. "

People who upload different types of content need tools that can create accessible social experiences. This includes adding alternatives to images and multimedia and using a clear link text that explains what the link is about.

**Comment by daniel-montalvo** [comment]
Hey @jade-mc 

I have updated the page based on your suggestions.

https://atag-briefs--wai-intro-atag.netlify.app/standards-guidelines/atag/social-media/

I am closing this issue as I think these suggestions are now addressed.

Feel free to open new issues if need be.
