### ISSUE TITLE
ATAG no code brief

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-intro-atag#35]
I haven't spent a great deal of time with this I'm afraid, but a couple of points. 

Perhaps more specific in the intro line?
This page briefly introduces a standard to help you make your no-code website tool accessible to creators, designers, and end users with disabilities.

I think the context here is a bit wider, so that makes it easier for the personas here (and they look pretty good as they are in my opinion). 

No comments on persona 1, I think the blocks of content example situates it comfortably in the no code context. 

For persona 2: the example in the persona suggests the booking system which is really useful, then it goes more general in the problem/solution part.  
'They can't book an appointment because my website has accessibility issues,' is there something more specific we can use here? Something about selecting dates/times/different stylists? Or drop down menus to be able to select and book different services?

Really simple edit for persona 3: 

Persona: Dacso runs a mechanic shop. He has a website where he puts videos that give customers short tips for fixing cars and motorbikes.

    Problem: " I have been told by my customers that my videos need captions,.... "

**Comment by daniel-montalvo** [comment]
Thanks much @jade-mc 
Adding these as GitHub tasks below.

- [ ] Perhaps more specific in the intro line?
This page briefly introduces a standard to help you make your no-code website tool accessible to creators, designers, and end users with disabilities.

I think the context here is a bit wider, so that makes it easier for the personas here (and they look pretty good as they are in my opinion). 

No comments on persona 1, I think the blocks of content example situates it comfortably in the no code context. 

- [ ] For persona 2: the example in the persona suggests the booking system which is really useful, then it goes more general in the problem/solution part.  
'They can't book an appointment because my website has accessibility issues,' is there something more specific we can use here? Something about selecting dates/times/different stylists? Or drop down menus to be able to select and book different services?

- [ ] Really simple edit for persona 3: 
Persona: Dacso runs a mechanic shop. He has a website where he puts videos that give customers short tips for fixing cars and motorbikes.

    Problem: " I have been told by my customers that my videos need captions,.... "

**Comment by daniel-montalvo** [comment]
Hey @jade-mc 

I have updated the page based on your suggestions.

https://atag-briefs--wai-intro-atag.netlify.app/standards-guidelines/atag/no-code/

I am closing this issue as I think these suggestions are now addressed.

Feel free to open new issues if need be.
