### ISSUE TITLE
[high] ATAG briefs [LMS] Rewrite example scenarios

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-intro-atag#48]
Here is how I would rewrite the rest of these:

Everyone can use previews
Scenario: Zola is a physics professor at a large university. She is blind and uses a screen reader that reads aloud the information on her screen.  Instructors who are blind and also those with auditory, cognitive, neurological, physical, and speech, disabilities need to be able to preview the course content before posting it for students just as other teachers do.
    Problem: " This system does not allow me to preview uploaded content for my students using my screen reader. I can't navigate the preview like I can a regular web page. "
    Works well: " The school purchased another LMS in which the content preview works just like a web page in a browser. I can navigate it easily using my screen reader's functionality. "

Everyone can edit content
Scenario: Aroon is a school administrator. Due to his quadriplegia, Aroon use speech recognition to navigate through applications and websites. Many people cannot use a mouse. They need to be able to use an LMS that works with their tools, such as speech recognition, keyboard, and switches.
    Problem: " I can't sort the course attendees data table within this system. There's no way to activate the column sort with voice. "
    Works well: " We switched to a system through which I can interact with the course attendees table by voice. I can select the column I want to sort by. "

**Comment by daniel-montalvo** [comment]
Thanks much @sharronrush 

We have added a more explanatory sentence now to define what "problem" and "works well" means. See [my comment for issue 46](https://github.com/w3c/wai-intro-atag/issues/46#issuecomment-1331026203)

Since these suggestions would imply further changes to the structure of all three briefs, I propose we stick with what we have for now and come back for further refinements after we publish the first iteration in December.

Are you OK with this approach? Is there any of these suggestions that you think we should implement before publishing this first iteration?

**Comment by sharronrush** [comment]
Happy with those changes, thank you
