### ISSUE TITLE
[med] ATAG briefs [no-code] explain no-code

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-intro-atag#49]
Some explanation of no-code is needed so people know they are in the right place. 
Suggestion:
No-code refers to tools that allow non-technical users to create software through an interface of pre-built templates and components. No knowledge of code languages is needed.

**Comment by shawna-slh** [comment]
I brought up in an EO meeting that likely we needed a different title and/or explanation of no-code tools. All disagreed. They said it's a well known term among those venders. And after looking around, I now agree with them.

Because this will be primarily pushed to non-code tool vendors, and likely not stumbled upon without context, I think we can do without additional explanation.

With that additional info, what do you think?

**Comment by sharronrush** [comment]
I don't agree but won't insist. We are assuming a lot with this approach it
seems to me.

**Comment by daniel-montalvo** [comment]
Thanks @sharronrush and @shawna-slh  for your input

Added at the beginning of [No-code intro section](https://atag-briefs--wai-intro-atag.netlify.app/standards-guidelines/atag/no-code/#why-accessibility-matters)

> No-code tools let people create websites without having to code.

Closing. Feel free to reopen in case you have wording suggestions for this.
